/** @type {import('prettier').Config} */

module.exports = {
  quoteProps: "consistent",
  singleQuote: false,
  trailingComma: "all",
  printWidth: 80,
  useTabs: false,
  bracketSpacing: true,
  semi: false,
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "",
    "^@/db",
    "^@/db/(.*)$",
    "",
    "<THIRD_PARTY_MODULES>",
    "",
    "^types$",
    "^@/types",
    "^@/types/(.*)$",
    "",
    "^@/config/(.*)$",
    "^@/lib/(.*)$",
    "^@/hooks/(.*)$",
    "^@/components/ui/(.*)$",
    "^@/components/(.*)$",
    "^@/styles/(.*)$",
    "^@/app/(.*)$",
    "",
    "^@/actions/(.*)$",
    "",
    "^[./]",
  ],
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  tailwindAttributes: ["tw"],
  tailwindFunctions: ["cva"],
  plugins: [
    "@ianvs/prettier-plugin-sort-imports",
    "prettier-plugin-tailwindcss",
  ],
}