name = "artoons"
compatibility_date = "2024-05-12"
node_compat = true

[dev]
port = 5000

[[unsafe.bindings]]
name = "ROOT_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 100, period = 60  }

[[unsafe.bindings]]
name = "IMAGES_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 100, period = 60 }

[[unsafe.bindings]]
name = "GENERATE_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 2, period = 60 }